require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe OpeningsController do

  # This should return the minimal set of attributes required to create a valid
  # Opening. As you add validations to Opening, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "opening_time" => "2013-02-25 16:49:32" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # OpeningsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all openings as @openings" do
      opening = Opening.create! valid_attributes
      get :index, {}, valid_session
      assigns(:openings).should eq([opening])
    end
  end

  describe "GET show" do
    it "assigns the requested opening as @opening" do
      opening = Opening.create! valid_attributes
      get :show, {:id => opening.to_param}, valid_session
      assigns(:opening).should eq(opening)
    end
  end

  describe "GET new" do
    it "assigns a new opening as @opening" do
      get :new, {}, valid_session
      assigns(:opening).should be_a_new(Opening)
    end
  end

  describe "GET edit" do
    it "assigns the requested opening as @opening" do
      opening = Opening.create! valid_attributes
      get :edit, {:id => opening.to_param}, valid_session
      assigns(:opening).should eq(opening)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Opening" do
        expect {
          post :create, {:opening => valid_attributes}, valid_session
        }.to change(Opening, :count).by(1)
      end

      it "assigns a newly created opening as @opening" do
        post :create, {:opening => valid_attributes}, valid_session
        assigns(:opening).should be_a(Opening)
        assigns(:opening).should be_persisted
      end

      it "redirects to the created opening" do
        post :create, {:opening => valid_attributes}, valid_session
        response.should redirect_to(Opening.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved opening as @opening" do
        # Trigger the behavior that occurs when invalid params are submitted
        Opening.any_instance.stub(:save).and_return(false)
        post :create, {:opening => { "opening_time" => "invalid value" }}, valid_session
        assigns(:opening).should be_a_new(Opening)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Opening.any_instance.stub(:save).and_return(false)
        post :create, {:opening => { "opening_time" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested opening" do
        opening = Opening.create! valid_attributes
        # Assuming there are no other openings in the database, this
        # specifies that the Opening created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Opening.any_instance.should_receive(:update_attributes).with({ "opening_time" => "2013-02-25 16:49:32" })
        put :update, {:id => opening.to_param, :opening => { "opening_time" => "2013-02-25 16:49:32" }}, valid_session
      end

      it "assigns the requested opening as @opening" do
        opening = Opening.create! valid_attributes
        put :update, {:id => opening.to_param, :opening => valid_attributes}, valid_session
        assigns(:opening).should eq(opening)
      end

      it "redirects to the opening" do
        opening = Opening.create! valid_attributes
        put :update, {:id => opening.to_param, :opening => valid_attributes}, valid_session
        response.should redirect_to(opening)
      end
    end

    describe "with invalid params" do
      it "assigns the opening as @opening" do
        opening = Opening.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Opening.any_instance.stub(:save).and_return(false)
        put :update, {:id => opening.to_param, :opening => { "opening_time" => "invalid value" }}, valid_session
        assigns(:opening).should eq(opening)
      end

      it "re-renders the 'edit' template" do
        opening = Opening.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Opening.any_instance.stub(:save).and_return(false)
        put :update, {:id => opening.to_param, :opening => { "opening_time" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested opening" do
      opening = Opening.create! valid_attributes
      expect {
        delete :destroy, {:id => opening.to_param}, valid_session
      }.to change(Opening, :count).by(-1)
    end

    it "redirects to the openings list" do
      opening = Opening.create! valid_attributes
      delete :destroy, {:id => opening.to_param}, valid_session
      response.should redirect_to(openings_url)
    end
  end

end
